development:
  adapter: postgresql
  encoding: unicode
  database: wolfpoint_development
  host: localhost
  pool: 5
  username: root
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: wolfpoint_test
  host: localhost
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: wolfpoint_production
  host: localhost
  pool: 5
  username: root
  password: